"""Cambia el tipo de dato de cantidad a String en RecetasIngredientes

Revision ID: ac980506ea14
Revises: 
Create Date: 2024-07-29 11:03:52.271731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac980506ea14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
